#!/bin/bash

scp ~/Desktop/get_next_line/get_next_line_bonus/get_next_line_bonus.c ubuntu@192.168.1.39:check/
scp ~/Desktop/get_next_line/get_next_line_bonus/get_next_line_utils_bonus.c ubuntu@192.168.1.39:check/
scp ~/Desktop/get_next_line/get_next_line_bonus/get_next_line_bonus.h ubuntu@192.168.1.39:check/
scp ~/Desktop/get_next_line/get_next_line_bonus/3 ubuntu@192.168.1.39:check/
scp ~/Desktop/get_next_line/get_next_line_bonus/4 ubuntu@192.168.1.39:check/
scp ~/Desktop/get_next_line/get_next_line_bonus/5 ubuntu@192.168.1.39:check/
scp ~/Desktop/get_next_line/get_next_line_bonus/6 ubuntu@192.168.1.39:check/
scp ~/Desktop/get_next_line/get_next_line_bonus/7 ubuntu@192.168.1.39:check/
scp ~/Desktop/get_next_line/get_next_line_bonus/main.c ubuntu@192.168.1.39:check/

cs50 gcc -Wall -Wextra -Werror -g3 -o check/gnl check/get_next_line_bonus.c check/get_next_line_utils_bonus.c check/main.c
